### ISSUE TITLE
Adding an OUT_SERVER_INFO listener breaks server status requests

### ISSUE THREAD

**Issue by ams2990** [dmulloy2/ProtocolLib#119] opened 2015-10-10 21:06 UTC
I created a PacketAdapter that listens to PacketType.Status.Server.OUT_SERVER_INFO packets and added an empty onPacketSending method. If I query the server using [Dinnerbone's status library](https://github.com/Dinnerbone/mcstatus), the server logs
> 2015-10-10 23:04:30 [WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException

and the server status library raises an error
> socket.error: [Errno 32] Broken pipe

Removing the PacketAdapter fixes the problem.

**Comment by dmulloy2** [comment] 2015-10-10 21:48
Use the latest dev build and set debug:true in the config.yml, it should print out some useful information that'll help me fix this.

**Comment by ams2990** [comment] 2015-10-10 22:28
Done. I also turned on detailed error messages.

    2015-10-11 00:26:39 [WARN] io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:281)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
    2015-10-11 00:26:39 [WARN]      at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    2015-10-11 00:26:39 [WARN]      at java.lang.Thread.run(Thread.java:745)
    2015-10-11 00:26:39 [WARN] Caused by: java.lang.RuntimeException: An internal error occured.
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:557)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
    2015-10-11 00:26:39 [WARN]      ... 18 more
    2015-10-11 00:26:39 [WARN] Caused by: java.io.IOException: Packet 1/0 (PacketStatusInStart) was larger than I expected, found 14 bytes extra whilst reading packet 0
    2015-10-11 00:26:39 [WARN]      at net.minecraft.server.v1_8_R3.PacketDecoder.decode(SourceFile:42)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    2015-10-11 00:26:39 [WARN]      at java.lang.reflect.Method.invoke(Method.java:497)
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
    2015-10-11 00:26:39 [WARN]      ... 20 more
    2015-10-11 00:26:39 [WARN] io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)
    2015-10-11 00:26:39 [WARN]      at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    2015-10-11 00:26:39 [WARN]      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
    2015-10-11 00:26:39 [WARN]      at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    2015-10-11 00:26:39 [WARN]      at java.lang.Thread.run(Thread.java:745)
    2015-10-11 00:26:39 [WARN] Caused by: java.lang.RuntimeException: An internal error occured.
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:557)
    2015-10-11 00:26:39 [WARN]      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
    2015-10-11 00:26:39 [WARN]      ... 19 more
    2015-10-11 00:26:39 [WARN] Caused by: java.io.IOException: Bad packet id 47
    2015-10-11 00:26:39 [WARN]      at net.minecraft.server.v1_8_R3.PacketDecoder.decode(SourceFile:37)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    2015-10-11 00:26:39 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    2015-10-11 00:26:39 [WARN]      at java.lang.reflect.Method.invoke(Method.java:497)
    2015-10-11 00:26:39 [WARN]      at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
    2015-10-11 00:26:39 [WARN]      ... 21 more
    2015-10-11 00:26:39 [WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

**Comment by dmulloy2** [comment] 2015-10-13 22:07
I was able to reproduce this, got a bunch of fun stacks: http://pastebin.com/j7NgHRuR

It looks like the channel gets closed in the time it takes to handle the packet. My best guess is that by trying to handle it on the main thread, ProtocolLib causes this issue.

I'll work on this some more when I get the chance. This'll be interesting - an actual bug with ProtocolLib.

**Comment by dmulloy2** [comment] 2015-10-17 02:16
I've narrowed down the cause of this, basically it's caused by trying to handle server pings on the main thread. By adding the async listener option to the packet listener, the issue is resolved. I'll look into fixing this on a ProtocolLib level.

**Closed** 2015-10-17 02:36 UTC
Labels: Bug

**Comment by ams2990** [comment] 2015-10-17 04:04
Confirmed fixed, thanks.
