### ISSUE TITLE
Having Trouble With the Maven Dependency

### ISSUE THREAD

**Issue by Jimmeh94** [dmulloy2/ProtocolLib#354] opened 2017-06-18 18:25 UTC
Hey there!

This is quite simple and I'm sure I'm overlooking something extremely easy, but for some reason, Maven can't resolve the ProtocolLib dependency I'm trying to use. Here's what I'm doing, as per the Spigot page:

`
        
        <repository>
            <id>dmulloy2-repo</id>
            <url>http://repo.dmulloy2.net/content/groups/public/</url>
        </repository>`

`
        
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib-API</artifactId>
            <version>4.3.0</version>
        </dependency>`

My apologies in advance if I'm missing something here. Thanks for any help!

**Comment by MiniDigger** [comment] 2017-06-18 19:11
duplicate of #353

**Closed** 2017-06-19 04:10 UTC
