### ISSUE TITLE
infinite spam errors

### ISSUE THREAD

**Issue by WareZ57** [dmulloy2/ProtocolLib#840] opened 2020-05-17 14:51 UTC
Hello,

I installed the ProtocolLib plugin with the latest build 451 on Jenkins. But this spam the console to infinity for no particular reason 1Go log few hours ..

Log error:
https://haste.chaun14.fr/fuzuzujapa.shell
Protocol dump:
https://haste.chaun14.fr/locoregedu.pl

Serveur Running on Mohist 1.12.2 hosted by Minstrator.com
Server plugin list :
![image](https://user-images.githubusercontent.com/7504466/82151924-707fe880-985e-11ea-8dd9-b908efa22180.png)

Thanks you.

**Comment by dmulloy2** [comment] 2020-05-24 19:31
Duplicate of https://github.com/dmulloy2/ProtocolLib/issues/843

**Closed by dmulloy2** 2020-05-24 19:31 UTC
