### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by DiamondTheo** [dmulloy2/ProtocolLib#458] opened 2018-04-02 13:19 UTC
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

Description and relevant errors:
it says chat cant be used
[2018-03-24-1.log.gz](https://github.com/dmulloy2/ProtocolLib/files/1868144/2018-03-24-1.log.gz)

**Comment by MiniDigger** [comment] 2018-04-02 15:18
how is this caused by protocollib? 
can you post a screenshot? 
I guess its caused by PEX being broken. you need to look into fixing that (or replacing it with LuckPerms like anybody else did)

**Comment by DiamondTheo** [comment] 2018-04-02 15:32
Ι dont have pex

**Comment by MiniDigger** [comment] 2018-04-02 15:33
you clearly have, based on that log...
> [11:28:06] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT-b148
[11:28:06] [Server thread/ERROR]: Error occurred while enabling PermissionsEx v2.0-SNAPSHOT-b148 (Is it up to date?)

**Comment by DiamondTheo** [comment] 2018-04-02 15:50
Wait i will check

**Comment by DiamondTheo** [comment] 2018-04-02 15:52
I didnt know i did i thought i removed it thanks again for the help

**Comment by MiniDigger** [comment] 2018-04-02 18:25
If this issue is resolved, make sure to close it.

**Comment by MiniDigger** [comment] 2018-04-02 21:52
Login into GitHub and press the close button.

**Comment by DiamondTheo** [comment] 2018-04-03 05:43
Thanks bye

**Closed** 2018-04-03 06:08 UTC
