### ISSUE TITLE
Console Spammed

### ISSUE THREAD

**Issue by Neweko** [dmulloy2/ProtocolLib#1062] opened 2021-01-11 19:51 UTC
So, I'm running minecraft 1.16.4, and the server starts up okay, so errors. BUT the instant someone joins the console is spammed forever with this error. >> https://paste.ajg0702.us/pudabedike.pl

**To Reproduce**
1. Install the plugin > ProtocolLib, any version. I tried the latest DEV version, the normal latest version, about ever version.
2. Start the server.
3. Join the server.

I expected there so be no errors.

The ERROR log >> https://paste.ajg0702.us/pudabedike.pl

Tried about 6 version, none worked. Server Version is 1.16.4

**Comment by PimvanderLoos** [comment] 2021-01-12 08:42
Duplicate of #1053 
Duplicate of #1055

Fixed by Holographic Displays in their [build 163](https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/).

**Comment by EmpathyHeals** [comment] 2021-01-18 13:08
Same issue? https://pastebin.com/6dacn8iE

**Closed** 2021-02-03 14:46 UTC
