### ISSUE TITLE
glowstone

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [dmulloy2/ProtocolLib#418] opened 2017-10-12 07:26 UTC
this is a support issue with a server type: 
please could you add support for glowstone some how i think they support this kind of thing its just the methods are different but ahhhhh once you add this i think that platform would expand very fast as it will expand plugin support

many thanks either way

MrGamerz

**Comment by MiniDigger** [comment] 2017-10-12 08:51
dupe of #308

**Comment by dmulloy2** [comment] 2017-10-13 02:06
To provide a status update: there was a fork created, but there doesn't appear to be any public work done yet

**Closed by dmulloy2** 2017-10-13 02:06 UTC
