### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by ElCunq** [dmulloy2/ProtocolLib#2115] opened 2023-01-19 18:34 UTC
protocolib gives me this error : [DetailedErrorReporter] Internal exception count: 4096!
after says Error Unable to intercept a read client packet.
and it also sends an message to minecraft chat. (it'll be in the files)
the error is also long I'll attach a txt file.
I couldn't understand why and don't know how to solve. That is the best information I can give. If this thread has oppened before sorry I couldn't see it.
![image](https://user-images.githubusercontent.com/112334725/213530452-34929549-5009-4828-bb1d-33cd1fb29ad2.png)
[Yeni Metin Belgesi.txt](https://github.com/dmulloy2/ProtocolLib/files/10460008/Yeni.Metin.Belgesi.txt)

**Comment by TheFaik** [comment] 2023-01-20 15:15
You are using legacy version 4.8.0, try to update to 5.0.0-SHAPSHOT, here is the link: https://ci.dmulloy2.net/job/ProtocolLib/606/
And by the way, my recommendation is not to use Spigot 1.19, try Paper or Purpur (better than him).

**Comment by ElCunq** [comment] 2023-01-21 13:29
> You are using legacy version 4.8.0, try to update to 5.0.0-SHAPSHOT, here is the link: https://ci.dmulloy2.net/job/ProtocolLib/606/ And by the way, my recommendation is not to use Spigot 1.19, try Paper or Purpur (better than him).

I'm using it on aternos server and aternos doesn't have snapshot versions so is there any way out of it?

**Comment by ItsQuadrus** [comment] 2023-01-21 19:27
Just wait until they update the plugin or contact them.

> > You are using legacy version 4.8.0, try to update to 5.0.0-SHAPSHOT, here is the link: https://ci.dmulloy2.net/job/ProtocolLib/606/ And by the way, my recommendation is not to use Spigot 1.19, try Paper or Purpur (better than him).
> 
> I'm using it on aternos server and aternos doesn't have snapshot versions so is there any way out of it?

**Comment by Gekko8** [comment] 2023-01-23 01:10
I am receiving the same error (screenshot below). I did try 5.0.0-SNAPSHOT and the servers failed to load completely. I will have to reproduce it to get the exact error from the log. Also, Issue #2116 looks to be a duplicate of this.

![image](https://user-images.githubusercontent.com/109000603/213950965-fcb9bc01-3fba-48a3-a4fe-5479dca990c4.png)

**Comment by Gekko8** [comment] 2023-01-23 01:23
A screenshot of the error using '5.0.0-SNAPSHOT' below and the log is attached.

![image](https://user-images.githubusercontent.com/109000603/213951683-080c28b9-8ff3-4250-b215-8a7c1b227263.png)
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/10476014/latest.log)

**Comment by Gekko8** [comment] 2023-01-25 05:59
I also tried the below versions, and all disconnect as the game connects and fail.
#612: Jan 14, 2023, 1:01 AM
#611: Jan 14, 2023, 12:57 AM
#610: Jan 10, 2023, 9:36 PM
#609: Jan 10, 2023, 3:44 AM
#608: Dec 18, 2022, 3:33 PM
#606: Dec 7, 2022, 6:52 PM

The only successful version is v4.8.0 for 1.8-1.18.x

**Closed** 2023-09-16 13:48 UTC
