### ISSUE TITLE
My Server crash all the time because of ProtocoLib

### ISSUE THREAD

**Issue by 7AGAM** [dmulloy2/ProtocolLib#1173] opened 2021-05-24 17:07 UTC
Her are my Logs -> https://mclo.gs/NQSgpFn

**Comment by PimvanderLoos** [comment] 2021-05-24 17:47
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by 7AGAM** [comment] 2021-05-25 08:42
What do I have to do to make it work again?

**Comment by PimvanderLoos** [comment] 2021-05-25 09:27
Try to download the latest dev-build (501, at the time of writing) linked above and use that version on your server instead.

**Comment by PimvanderLoos** [comment] 2021-05-25 13:55
Nope, in that case I'm afraid you'll have to wait for @dmulloy2 to publish the update on Spigot.

**Closed** 2024-06-12 02:59 UTC
