### ISSUE TITLE
PacketPlayOutEntityDestroy

### ISSUE THREAD

**Issue by StevenDouillet** [dmulloy2/ProtocolLib#1351] opened 2021-07-23 15:10 UTC
The warning log : 
![image](https://user-images.githubusercontent.com/41373474/126801893-2043e55b-ea76-4a68-9ba4-15001f1dc20d.png)

Using : 
- reproduced on protocol lib versions 4.7.0 and 4.7.1
- holographic display last version 2.4.8
- beautyquest last version 0.19
- airplane 1.17

I can not reproduce it, just lauching my server with theses 3 plugins at least and get this warn every x seconds (randomly but very often)

**Comment by alexandrage** [comment] 2021-07-24 10:09
Same problem how to get IntList?

**Comment by WcaleNieWolny** [comment] 2021-07-24 11:40
I had the same problem.  To reproduce do this: `    public void sendRealDespawnPacket(Player reciver) {
        PacketContainer deSpawnPacket = new PacketContainer(PacketType.Play.Server.ENTITY_DESTROY);
        WrapperPlayServerEntityDestroy deSpawnPacketWrapper = new WrapperPlayServerEntityDestroy(deSpawnPacket);
        System.out.println(knocked.getEntityId());
        int[] idlist = new int[]{knocked.getEntityId()};
        System.out.println(Arrays.toString(idlist));
        try {
            deSpawnPacketWrapper.setEntityIds(idlist);
            ProtocolManager pm = ProtocolLibrary.getProtocolManager();
            pm.sendServerPacket(reciver, deSpawnPacket);
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }` version of protocollib: 
![image](https://user-images.githubusercontent.com/50914789/126867287-e600929f-53e8-4876-afd5-467a3107a10f.png)

**Comment by WcaleNieWolny** [comment] 2021-07-24 12:14
If u want to make despawn packet work on 1.17  do `deSpawnPacket.getModifier().write(0, new IntArrayList(new int[]{ENTITYID}));`

**Comment by PimvanderLoos** [comment] 2021-07-27 17:57
As mentioned in filoghost/HolographicDisplays#499, the specific issue shown by OP has been fixed by HolographicDisplays in version 2.4.9.

**Comment by ItzAmirreza** [comment] 2021-07-28 18:28
Funny because now it is back to the previous protocol setting for 1.17.1 and even if you do use the previous setting, it doesn't destroy the entity

**Closed** 2024-06-12 02:59 UTC
