### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darkspand** [dmulloy2/ProtocolLib#1189] opened 2021-05-31 20:58 UTC
[06:01:11] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[06:01:11] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalAccessError: tried to access class com.comphenix.protocol.injector.netty.ProtocolInjector$1 from class com.comphenix.protocol.injector.netty.ProtocolInjector
  	at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:144)
  	at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:887)
  	at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393)
  	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:382)
  	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:341)
  	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:208)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@28d40c51[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5c27b816
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@25a5d283
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@398d4eb0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@31336b54
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5035926c
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@75965bd2
        reporter=com.comphenix.protocol.ProtocolLib$1@5b0f6323
        server=CraftServer{serverName=NachoSpigot,serverVersion=1.8.8,minecraftVersion=1.8.8}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2267eda7
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@49e36a55
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7a063019
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@5a72e028[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2b0a1528
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5c27b816
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@79e973de
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@32a41202
      commandProtocol=com.comphenix.protocol.CommandProtocol@7f9ac7de
      commandPacket=com.comphenix.protocol.CommandPacket@4c23e50
      commandFilter=com.comphenix.protocol.CommandFilter@3607da95
      packetLogging=com.comphenix.protocol.PacketLogging@2421ea55
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@10524085
      server=CraftServer{serverName=NachoSpigot,serverVersion=1.8.8,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@3b0a7398
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@75965bd2
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@2ecf6d1
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    1.8.0_231
  Server:
    1.8.8 (MC: 1.8.8)

[06:01:11] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.6.0

**Comment by PimvanderLoos** [comment] 2021-06-01 11:01
Duplicate of #1162

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by darkspand** [comment] 2021-06-01 16:21
I use NachoSpigot. In this version, ProtocolLib does not work, but when running the normal spigot version, ProtocolLib is active

**Comment by PimvanderLoos** [comment] 2021-06-01 16:47
Ah, yeah, I see I replied too hastily and that this is a completely different issue. My apologies.

**Closed** 2021-06-04 22:08 UTC
