### ISSUE TITLE
protocollib + viaversion = conflict

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2419] opened 2023-06-07 16:30 UTC
Console Error
https://paste.gg/p/anonymous/fba5187f8d31461eaaa5f4a2ae4682f0

Bug Description
viaversion conflict

support says: The error isn't ViaVersion related

**Comment by lukalt** [comment] 2023-06-07 16:44
Which Java Version and JVM (Hotspot vs OpenJ9) are you using?

**Comment by F3F5** [comment] 2023-06-07 16:45
and i don't reloaded protocollib, it only with viaversion installed caused this random erorrs

**Comment by Draghonir** [comment] 2023-06-07 21:47
Hello same way for me 

<img width="1719" alt="1" src="https://github.com/dmulloy2/ProtocolLib/assets/107469643/d2397227-2c9f-481f-9a0e-a50f4a8efc2e">
<img width="781" alt="2" src="https://github.com/dmulloy2/ProtocolLib/assets/107469643/ae874623-d32d-42a8-8bdb-37a645b374cf">

**Comment by Draghonir** [comment] 2023-06-07 21:48
https://spark.lucko.me/alxpcKUQAY if you need info from my server

**Comment by F3F5** [comment] 2023-06-08 07:47
https://pastes.dev/1bl5AMAGxH

**Comment by lukalt** [comment] 2023-06-08 16:27
@F3F5 Please try build 649: https://ci.dmulloy2.net/job/ProtocolLib/649/. The problem should be fixed now

**Comment by F3F5** [comment] 2023-06-08 16:34
> @F3F5 Please try build 649: https://ci.dmulloy2.net/job/ProtocolLib/649/. The problem should be fixed now

same issues

**Comment by F3F5** [comment] 2023-06-08 16:34
https://pastes.dev/NHzv3hIbWK

**Comment by mxson** [comment] 2023-06-08 16:59
the issue is still occurring for myself as well

**Comment by lukalt** [comment] 2023-06-08 18:47
I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

**Comment by F3F5** [comment] 2023-06-08 18:50
> I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

can you look at our problem

**Comment by lukalt** [comment] 2023-06-08 19:23
I have absolutely no clue how this could be caused. Maybe @derklaro can help here

**Comment by Draghonir** [comment] 2023-06-08 19:26
> I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

is fixed for me ;)

**Comment by derklaro** [comment] 2023-06-08 19:50
Is there no other error while starting up the server that is related to ProtocolLib? (search for the log message `Unable to retrieve trusted lookup`)

**Comment by F3F5** [comment] 2023-06-09 08:08
> Is there no other error while starting up the server that is related to ProtocolLib? (search for the log message `Unable to retrieve trusted lookup`)

no

**Comment by F3F5** [comment] 2023-06-10 19:05
@dmulloy2 please check :0

**Closed** 2023-06-11 12:29 UTC
