### ISSUE TITLE
Doesn't work on OpenJ9

### ISSUE THREAD

**Issue by DanielUchilah** [dmulloy2/ProtocolLib#2516] opened 2023-08-23 08:01 UTC
- [ ] This issue is not solved in a development build

**Describe the bug**
ProtocolLib doesn't work on OpenJ9 Java version.

**To Reproduce**
1. Use any version of 'OpenJ9 java' on the server
2. Start the server
3. ProtocolLib doesn't enable
4. See error in console

**Expected behavior**
ProtocolLib work fine.

**Screenshots**
None

**Version Info**
https://pastebin.com/kKT4j6hH

**Additional context**
On regular JAVA works fine. This looks for me a must do fix because the OpenJ9 its 3x more optimized compared to regular java.

**Comment by derklaro** [comment] 2023-08-23 08:05
Duplicate of #2507
To be clear: due to restrictions that the jvm made to reflection we cannot support openj9, as we're relying on some (rather unsafe) mechanics to make reflections still work without breaking backwards compatibility.

**Closed** 2024-06-12 03:08 UTC
