### ISSUE TITLE
Error Can't Compile Structure. Disabling Compiler.

### ISSUE THREAD

**Issue by Illustive** [dmulloy2/ProtocolLib#1182] opened 2021-05-26 22:00 UTC
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6c0b7224
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@731dc347[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.BlockPosition net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.a, public net.minecraft.server.v1_16_R3.IBlockData net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.block]
      defaultFields={private net.minecraft.server.v1_16_R3.BlockPosition net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@45904d4b[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@30642e1c
        packetListeners=[PacketAdapter[plugin=AAC5, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], FLYING[class=PacketPlayInFlying, id=21], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION[class=PacketPlayOutPosition, id=52], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], POSITION[class=PacketPlayInPosition, id=18], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=LOW, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], FLYING[class=PacketPlayInFlying, id=21], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION[class=PacketPlayOutPosition, id=52], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], POSITION[class=PacketPlayInPosition, id=18], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6eade12
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1bf02273
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5c4dce53
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d481f08
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib (1).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@1d0242fd
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-730,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3576617e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e4ad0f6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@aa16218
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@34c84cfd[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@5c33f2d2=[com.comphenix.protocol.injector.StructureCache$1@5590aaa2], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@e471133e=[com.comphenix.protocol.injector.StructureCache$1@6de50d86]}
      listenerLock=java.lang.Object@6c550380
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@1a8c1553
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@4a99791a
      reporter=com.comphenix.protocol.ProtocolLib$1@1d0242fd
      unknownPermGenBean=java.lang.Object@fd5c4f2
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-730 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment] 2021-05-27 16:52
Duplicate of #1162

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-05-29 17:02 UTC
