### ISSUE TITLE
1.20.5

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#2903] opened 2024-04-29 18:19 UTC
Its not working

**Comment by Jeppa** [comment] 2024-05-01 13:10
Yes, latest build (#686) throws an error here, too.
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket when  calling com.comphenix.protocol.ProtocolLibrary.getProtocolManager().createPacket(com.comphenix.protocol.PacketType.Play.Server.PLAYER_INFO)

**Comment by jurohn** [comment] 2024-05-01 16:59
https://pastebin.com/r33gb2UK

1.20.6 Error dump

**Comment by LoneDev6** [comment] 2024-05-02 14:57
Duplicate of https://github.com/dmulloy2/ProtocolLib/issues/2900
Please close.

**Comment by 0bviouslee** [comment] 2024-05-04 17:30
> > Duplicate of #2900 Please close.
> 
> Its still not working (2024-05-04)

why are you rushing the release every single day lol, you aren't even waiting til a new build comes out

**Comment by Jeppa** [comment] 2024-05-04 17:34
> Its still not working (2024-05-04)

Without a new release: sure...

**Closed** 2024-05-06 17:02 UTC
