### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR

### ISSUE THREAD

**Issue by Patrick12300** [dmulloy2/ProtocolLib#1171] opened 2021-05-23 15:59 UTC
[17:48:38 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5f6efe11
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@41731776[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7c94c0c9[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6da22a8f
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@129494bc, com.comphenix.protocol.async.NullPacketListener@788f3bf6, com.comphenix.protocol.async.NullPacketListener@1b0f8db4]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3a0c9dd7
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@639de547
        inputBufferedPackets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29], POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@39d5e375
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@455f4092
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@1b638fcb
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-715,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@18061f8
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6b4a6427
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@72e3e37e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@3a6f5e9f[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@90c70871=[com.comphenix.protocol.injector.StructureCache$1@69c1d3e3]}
      listenerLock=java.lang.Object@5192e9a0
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@3c8708ff
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@7c5c2256
      reporter=com.comphenix.protocol.ProtocolLib$1@1b638fcb
      unknownPermGenBean=java.lang.Object@1b65a8f5
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-715 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment] 2021-05-24 11:14
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-05-29 17:05 UTC
