### ISSUE TITLE
Error (unable to retrieve current version) being thrown during Paper 1.21 startup

### ISSUE THREAD

**Issue by jk33v3rs** [dmulloy2/ProtocolLib#3099] opened 2024-07-08 18:14 UTC
- [x] This issue is not solved in a development build

**Describe the bug**
[17:55:16] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.3.0-SNAPSHOT-723
[17:55:16] [Server thread/WARN]: [ProtocolLib] [ProtocolLib] Unable to retrieve current Minecraft version. Assuming (MC: 1.20.4)
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at ProtocolLib.jar/com.comphenix.protocol.ProtocolConfig.getIgnoreVersionCheck(ProtocolConfig.java:297) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.ProtocolLib.verifyMinecraftVersion(ProtocolLib.java:376) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:168) ~[ProtocolLib.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-47-62ed302]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-47-62ed302]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-47-62ed302]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-47-62ed302]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-47-62ed302]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-47-62ed302]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[paper-1.21.jar:1.21-47-62ed302]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-47-62ed302]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**To Reproduce**

**Expected behavior**
Find version 1.21 or 1.21_R1 as other plugins do

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

https://pastebin.com/70CfA7sh

**Additional context**
LibsDisguises is also in the plugins folder but doesnt seem to have a listener listed

**Comment by Ingrim4** [comment] 2024-07-08 19:50
Duplicate of #3072

**Closed by Ingrim4** 2024-07-08 19:50 UTC
Labels: config, duplicate
