### ISSUE TITLE
Idk what bug is this i am just opening a server with the plugins ty!

### ISSUE THREAD

**Issue by AgentYoutuber** [dmulloy2/ProtocolLib#1166] opened 2021-05-21 07:04 UTC
When I open and join my server, it shows these:
[14:55:07 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @16b15fc0
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@7a521aa[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4c555b56[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4acf07ce
        packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayOutPosition, id=52], POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayOutPosition, id=52], POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5e9a4758
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@701c9550
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@16f5ffee
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@24b67b89
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@289a48c0
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-670,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@50b7c60
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4d51ba1f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6eaf0333
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@30f9800[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@642e5143=[com.comphenix.protocol.injector.StructureCache$1@29a158da]}
      listenerLock=java.lang.Object@69608eb3
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@7fc0be37
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@70f657
      reporter=com.comphenix.protocol.ProtocolLib$1@289a48c0
      unknownPermGenBean=java.lang.Object@23b4090b
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-670 (MC: 1.16.5)

**Screenshots**
![image](https://user-images.githubusercontent.com/84561722/119096065-b2c9a000-ba45-11eb-96a5-3cdf7b72313f.png)
![image](https://user-images.githubusercontent.com/84561722/119096135-c6750680-ba45-11eb-9288-95de4e2dc4dc.png)

**Version Info**
https://pastebin.com/raw/iuV7dfJy

My plugins:
AdvancedBan, AntiCheatReloaded, AureliumSkills, AuthMe, BedRegen, ClearLag, CSM, CustomWings, DefensiveTurrets, DeluxeHub, DiscordSRV, DualWield*, EconomyShopGUI, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, GroupManager, IPortal, Multiverse-Core, Multiverse-Inventories, ProtocolLib, ReviveMe, SecurityCams, SkQuery, Skript, SmoothTimber, StaffPlus, TAB, TigerReports, UltraCosmetics, Vault, WorldEdit

**Comment by PimvanderLoos** [comment] 2021-05-21 11:00
Duplicate of #1164

This issue is resolved in [dev-build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by AgentYoutuber** [comment] 2021-05-26 08:52
ty!

**Closed** 2021-05-29 17:07 UTC
