### ISSUE TITLE
Holograms plugin error to protocollib

### ISSUE THREAD

**Issue by supermem99** [dmulloy2/ProtocolLib#1064] opened 2021-01-14 02:09 UTC
**Describe the bug**
I updated to the latest version and this was sent to me.
I get this on join 

**Screenshots**
[click](https://pastebin.com/XvSmQxnM)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
[click](https://pastebin.com/LnWe6LMg)

**Additional context**
i use paper 1.16.4 latest

**Comment by PimvanderLoos** [comment] 2021-01-14 11:11
Duplicate of #1053
Duplicate of #1055
Duplicate of #1062

Fixed by Holographic Displays in their [build 163](https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/).

**Closed** 2021-06-22 22:30 UTC
