### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by HAG0S** [dmulloy2/ProtocolLib#1177] opened 2021-05-25 10:25 UTC
I'm getting this warning
![Screen Shot 2021-05-25 at 6 23 43 pm](https://user-images.githubusercontent.com/77733753/119482348-58527b80-bd86-11eb-9fb6-734a854dd6e3.png)

**Comment by PimvanderLoos** [comment] 2021-05-25 14:00
Duplicate of #1167 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-05-29 17:04 UTC
