### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by mapacheee** [dmulloy2/ProtocolLib#1172] opened 2021-05-23 22:57 UTC
Hi, i have an error:
https://pastebin.com/X3sjDg2r

Java 16, purpur and mc 1.16.5

**Comment by PimvanderLoos** [comment] 2021-05-24 11:14
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-05-29 17:04 UTC
