### ISSUE TITLE
Error: cannot compile structure, disbling compiler

### ISSUE THREAD

**Issue by TsunayoshiSawada** [dmulloy2/ProtocolLib#1319] opened 2021-07-07 15:04 UTC
**Describe the bug**
I got no idea what im reporting

```
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1391eadd
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@29365b16[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5275693a[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4d6a01fa
        packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@32da9d44
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@292f9ee2
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50ea1e44
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d92b072
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2b442439
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-778,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7e515e9e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6de30f2a
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@81ecad0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1b12a9ae[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@365554dc=[com.comphenix.protocol.injector.StructureCache$1@1290c607]}
      listenerLock=java.lang.Object@67ff1120
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@19c91f45
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@17989a0b
      reporter=com.comphenix.protocol.ProtocolLib$1@2b442439
      unknownPermGenBean=java.lang.Object@32cc601
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-778 (MC: 1.16.5)

[20:30:16 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1391eadd
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@29365b16[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5275693a[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4d6a01fa
        packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@32da9d44
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@292f9ee2
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50ea1e44
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d92b072
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2b442439
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-778,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7e515e9e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6de30f2a
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@81ecad0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1b12a9ae[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@365554dc=[com.comphenix.protocol.injector.StructureCache$1@1290c607]}
      listenerLock=java.lang.Object@67ff1120
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@19c91f45
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@17989a0b
      reporter=com.comphenix.protocol.ProtocolLib$1@2b442439
      unknownPermGenBean=java.lang.Object@32cc601
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-778 (MC: 1.16.5)
```

**Comment by JNachow** [comment] 2021-07-08 16:42
I have the same issue. Spigot 1.6.5 and java 16.

Upgrading spigot is not the way to go now as it breaks a lot of plugins. Subscribed so I get notified when solution is pushed.

 java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @398f2e54
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@7fa7a4ef[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutChat
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]
      defaultFields={public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components=1, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b=2, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c=3}
      subtypeCache={class java.util.UUID=StructureModifier[fieldType=class java.util.UUID, data=[private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5eb75760[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1cf50085
        packetListeners=[PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=TutorialCreator, sending=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=PacketPlayOutChat, id=14]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7794074b
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2f89d767
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4b6199a1
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7fa44960
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@4d043fe7
        reporter=com.comphenix.protocol.ProtocolLib$1@285db780
        server=CraftServer{serverName=CraftBukkit,serverVersion=3092-Spigot-9fb885e-ebe18b9,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@e654b02
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@82640ce
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@647ab5e9
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6f872f2c[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@ea375052=[com.comphenix.protocol.injector.StructureCache$1@3af526ef], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@f85029d=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@ef214f]}
      listenerLock=java.lang.Object@318b1946
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@67a3ae14
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@74722e51
      reporter=com.comphenix.protocol.ProtocolLib$1@285db780
      unknownPermGenBean=java.lang.Object@d6e8cc9
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    3092-Spigot-9fb885e-ebe18b9 (MC: 1.16.5)

**Comment by dmulloy2** [comment] 2021-07-08 17:20
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)

**Closed by dmulloy2** 2021-07-08 17:20 UTC

**Comment by JNachow** [comment] 2021-07-08 17:54
Commenting in case someone else has experienced an issue. 

after installing the dev build mentioned by @dmulloy2  I get an error on another plugin called spartan:
` Error occurred while enabling Spartan vBuild 417.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.comphenix.protocol.PacketType com.comphenix.protocol.PacketType$Play$Client.valueOf(java.lang.String)'
        at me.vagdedes.spartan.g.m.R(PlibHandlers.java:39) ~[?:?]
        at me.vagdedes.spartan.b.a.b.a.k(BackgroundProtocolLib.java:36) ~[?:?]
        at me.vagdedes.spartan.b.a.b.b.f(ProtocolLib.java:32) ~[?:?]
        at me.vagdedes.spartan.c.b.f(Compatibility.java:137) ~[?:?]
        at me.vagdedes.spartan.c.c.n(Config.java:320) ~[?:?]
        at me.vagdedes.spartan.Register.onEnable(Register.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3092-Spigot-9fb885e-ebe18b9]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

Error was not present beforehand as the error was the one mentioned above in this ticket.

expected result:
`[19:46:55] [Server thread/INFO]: [Spartan] Enabling Spartan vBuild 417.1
[19:46:56] [pool-28-thread-1/INFO]: [Spartan Notification] Done loading 25 rows of data to the Search Engine.
`

We rolled back to the previous build we had of the server (that should have the "at the top" mentioned bug present) and for some reason that bug is now gone. Pretty weird that we just rebuild the image and the issue is now solved.

**Comment by IllusionTheDev** [comment] 2021-07-09 02:34
That's seems like an issue with Spartan, not ProtocolLib
