### ISSUE TITLE
Console told me to send:

### ISSUE THREAD

**Issue by Methusalem1970** [dmulloy2/ProtocolLib#1184] opened 2021-05-29 18:58 UTC
[20:54:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disa                                                                             bing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final                                                                              java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,in                                                                             t) throws java.lang.ClassFormatError accessible: module java.base does not "open                                                                             s java.lang" to unnamed module @421782e
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Ac                                                                             cessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Ac                                                                             cessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:                                                                             199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateCla                                                                             ss(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(Str                                                                             uctureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(Bac                                                                             kgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo                                                                             lExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo                                                                             olExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@2ca1d10e[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompo                                                                             und.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4bb4903b[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@40b29910
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWh                                                                             itelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSou                                                                             ndEffect, id=81], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gameph                                                                             ase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsD                                                                             isguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=                                                                             PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21], S                                                                             ET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=P                                                                             acketPlayInWindowClick, id=9], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id                                                                             =37]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIG                                                                             H, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=                                                                             PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlo                                                                             t, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], HELD_ITEM_SLOT[cla                                                                             ss=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAda                                                                             pter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[NA                                                                             MED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[cla                                                                             ss=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE_LOOK[class=PacketPlayOut                                                                             RelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=                                                                             39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_VELOCIT                                                                             Y[class=PacketPlayOutEntityVelocity, id=70], ATTACH_ENTITY[class=PacketPlayOutAt                                                                             tachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], ENTITY_HEAD_R                                                                             OTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=Packe                                                                             tPlayOutEntityStatus, id=26], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=                                                                             89], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_TELEP                                                                             ORT[class=PacketPlayOutEntityTeleport, id=86], ENTITY_LOOK[class=PacketPlayOutEn                                                                             tityLook, id=41]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@                                                                             62b919a9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4                                                                             @585cd83f
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerLi                                                                             st@3706be47
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerLis                                                                             t@63a8cbae
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=t                                                                             rue, url=plugins/ProtocolLib4.6.0.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4976e223
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-744,minecraf                                                                             tVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@75a32                                                                             a29
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1f4                                                                             c5567
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@54a05b2c
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2d59c4e2[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$Struc                                                                             tureKey@afcc04db=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@4                                                                             8342264], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey                                                                             @ad7bd490=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@35aea168                                                                             ]}
      listenerLock=java.lang.Object@6301e5ca
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@1c539c
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorServic                                                                             e@69d266f9
      reporter=com.comphenix.protocol.ProtocolLib$1@4976e223
      unknownPermGenBean=java.lang.Object@29372f4a
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-744 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment] 2021-05-31 20:29
Duplicate of #1162

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-06-04 22:10 UTC
