### ISSUE TITLE
Unable to start in paper1.8.8

### ISSUE THREAD

**Issue by NeglectDream** [dmulloy2/ProtocolLib#2372] opened 2023-04-29 08:52 UTC
The following error occurred

[16:43:57] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-636
[16:43:58] [Server thread/WARN]: java.lang.IllegalStateException: Unable to access field private final org.bukkit.craftbukkit.v1_8_R3.CraftWorld net.minecraft.server.v1_8_R3.World.world
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:56)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.BukkitConverters.<clinit>(BukkitConverters.java:127)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.instances.MinecraftGenerator.<clinit>(MinecraftGenerator.java:30)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.instances.DefaultInstances.<clinit>(DefaultInstances.java:40)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.getDefaultGenerator(StructureModifier.java:134)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.<clinit>(StructureModifier.java:57)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:115)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:294)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175)
[16:43:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[16:43:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[16:43:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[16:43:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:823)
[16:43:58] [Server thread/WARN]: Caused by: 
[16:43:58] [Server thread/WARN]: java.lang.IllegalAccessException: illegal setter on final field
[16:43:58] [Server thread/WARN]: 	at java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:808)
[16:43:58] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
[16:43:58] [Server thread/WARN]: 	... 17 more
[16:43:58] [Server thread/ERROR]: null initializing ProtocolLib v5.0.0-SNAPSHOT-636 (Is it up to date?)
java.lang.NullPointerException: null
	at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:394) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87) ~[?:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:186) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [%5b%e7%ba%af%e5%87%80%e6%a0%b8%e5%bf%83%5d%5b1.8.8%5dPaperSpigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [%5b%e7%ba%af%e5%87%80%e6%a0%b8%e5%bf%83%5d%5b1.8.8%5dPaperSpigot.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [%5b%e7%ba%af%e5%87%80%e6%a0%b8%e5%bf%83%5d%5b1.8.8%5dPaperSpigot.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]

**Comment by lukalt** [comment] 2023-05-01 11:20
Seems to be a duplicate of #1930. Please use ProtocolLib 4.8.0 for now: https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0

**Comment by pabloalba16** [comment] 2023-05-17 23:07
Same error, it happens while running java 8, 11 or 16 on openj9

**Comment by lukalt** [comment] 2023-05-17 23:50
Does the problem occur with Hotspot as well?

**Comment by pabloalba16** [comment] 2023-05-21 11:59
no, in hotspot runs fine

**Comment by pabloalba16** [comment] 2023-05-21 11:59
also java 17 openj9 and hotstop runs fine too

**Closed as completed** 2024-06-12 03:07 UTC
