### ISSUE TITLE
Advanedgui error - cpu raises randomly

### ISSUE THREAD

**Issue by supermem99** [dmulloy2/ProtocolLib#1585] opened 2022-04-30 10:46 UTC
**Describe the bug**
I use the plugin advancedgui, which integrated protocollib. I have the latest version of both and on start up this error logs causes spam and high cpu.  https://just-paste.it/Sys34SQj4E[https://just-paste.it/Sys34SQj4E](https://just-paste.it/Sys34SQj4E) 
**To Reproduce**
1. Install latest protocollib and advacedgui 
2. Start server
3. Error ocur
4. See spam and cpu raises randomly

**Expected behavior**
No error should occur

**Screenshots**
No

**Version Info**
https://just-paste.it/H07FJrs541[https://just-paste.it/H07FJrs541](https://just-paste.it/H07FJrs541) 

**Additional context**
Advancedgui told me that its not their issue

**Comment by CloudeLecaw** [comment] 2022-05-03 04:23
We also have this im not sure bit it lools simliar to yours.

We got this issue with procollib 5 and also with the 4.8 version from spigots site

https://www.toptal.com/developers/hastebin/qucufavuhu.properties

**Comment by supermem99** [comment] 2022-05-03 08:55
Its the same, thx

**Comment by CloudeLecaw** [comment] 2022-05-03 10:11
Well Problem is the FreezeFixnsetting that is turned on in newer Spigot/Paper Versions even if it should not.
The dev allready sendet me anfixed AdvancedGUI.jar. I think it will be released soon. So the issues was with AdvanedGUI andni think the ticket itself can be closed for now:)

**Comment by DevLeoko** [comment] 2022-05-03 11:06
This is a duplicate of #1401

**Comment by derklaro** [comment] 2022-05-20 15:17
All of the posted error logs don't work anymore, please repost them to pastebin to keep them up 👍

**Closed** 2024-06-12 03:00 UTC
