### ISSUE TITLE
ProtocolLib 698

### ISSUE THREAD

**Issue by Daniel-Yablochkin** [dmulloy2/ProtocolLib#2968] opened 2024-06-04 08:36 UTC
[11:01:07 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder

java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([570...33])

at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[LoneLibs.jar:?]

at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[LoneLibs.jar:?]

at ia.m.hG.onPacketSending(SourceFile:186) ~[ItemsAdder_3.6.4.jar:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]

at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]

at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]

at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1647) ~[?:?]

at net.minecraft.world.entity.vehicle.ContainerEntity.interactWithContainerVehicle(ContainerEntity.java:91) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.world.entity.vehicle.MinecartChest.interact(MinecartChest.java:66) ~[?:?]

at net.minecraft.world.entity.player.Player.interactOn(Player.java:1168) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2973) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2993) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2932) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]

at java.lang.Thread.run(Thread.java:840) ~[?:?]

Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([570...33])

at net.minecraft.util.GsonHelper.convertToString(GsonHelper.java:94) ~[?:?]

at net.minecraft.util.GsonHelper.getAsString(GsonHelper.java:100) ~[?:?]

at net.minecraft.network.chat.HoverEvent$EntityTooltipInfo.create(HoverEvent.java:177) ~[?:?]

at net.minecraft.network.chat.HoverEvent$Action.deserialize(HoverEvent.java:136) ~[?:?]

at net.minecraft.network.chat.HoverEvent.deserialize(HoverEvent.java:80) ~[?:?]

at net.minecraft.network.chat.Style$Serializer.getHoverEvent(Style.java:405) ~[?:?]

at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:377) ~[?:?]

at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:364) ~[?:?]

at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]

at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]

at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:361) ~[?:?]

at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:222) ~[?:?]

at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]

at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]

at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:536) ~[?:?]

at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[LoneLibs.jar:?]

... 42 more

[11:01:07 ERROR]: Parameters:

net.minecraft.network.protocol.game.PacketPlayOutOpenWindow@54621e12[

a=1

b=net.minecraft.world.inventory.Containers@7c11fc3d

c=translation{key='entity.minecraft.chest_minecart', args=[]}[style={hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@12351809'},insertion=21fc2682-1532-4b1c-8a7b-5aa748e55999}]

]

**Comment by dmulloy2** [comment] 2024-06-05 03:44
Dupe of #2967

**Closed by dmulloy2** 2024-06-05 03:44 UTC
