### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by jurohn** [dmulloy2/ProtocolLib#2907] opened 2024-05-02 09:35 UTC
Paper 1.20.6 dev build #35

Error from protocollib (also the reason PL-HIDE-PRO doesnt work now)

https://pastebin.com/yk0ZvPmQ

**Comment by LoneDev6** [comment] 2024-05-02 14:56
Duplicate of #2900
Please close.

**Comment by Budderman18** [comment] 2024-05-03 19:45
> > Duplicate of #2900 Please close.
> 
> It can be closed when 1.20.6 is added 👍

he isnt telling you to close it because they aren't going to update to 1.20.6, its because the issue already exists and this one is completely useless

**Closed** 2024-05-06 17:02 UTC
