### ISSUE TITLE
NullPointer 1.8 server with 1.17 protocollib

### ISSUE THREAD

**Issue by zKaanGit** [dmulloy2/ProtocolLib#1275] opened 2021-06-27 08:38 UTC
**Describe the bug 1**
Since I switched from build #521 to build #523 this error appears, whats wrong, or isnt there backwards compatible?
Error: https://paste.gg/p/anonymous/164d61eb3e014a67aa5e108ccd8100b0
Code: https://paste.gg/p/anonymous/da1f3c94074f4ec48b49c80faaf4b5e9
Server: 1.8.8 Paper Fork

**Describe the bug 2**
Since protocollib 1.17 the FLYING field isnt working.
Error: https://pastebin.com/fbQdMaxL
Server: 1.16.5 Paper

**Comment by derklaro** [comment] 2021-06-27 08:44
Duplicate of #1274

**Comment by zKaanGit** [comment] 2021-06-27 08:48
these three minutes he was faster... what a coincidence. But the second bug he dont have :P

**Closed** 2021-06-27 22:13 UTC
