### ISSUE TITLE
Critical Hits stopped working

### ISSUE THREAD

**Issue by LucidAPs** [dmulloy2/ProtocolLib#1841] opened 2022-08-13 06:44 UTC
Critical Hits stopped working on 1.19.2 servers with the build [#593](https://ci.dmulloy2.net/job/ProtocolLib/593/) and up.

Edit: The damage on weapons are messed up aswell. All weapons do 1 heart.

Edit: Going back to builds that came out on the 7th fixes the damage/crits issue.

**Comment by Wamens** [comment] 2022-08-13 14:38
I got the same issues aswell, although I can't find the builds that released on the 7th. Are you able to send me the file discord is Wamens#0001

**Comment by QuantumC07** [comment] 2022-08-13 14:42
Same as Wamens. Mind sending me the file too? Discord is Smeo#2833

**Comment by PadawanAmy** [comment] 2022-08-13 18:09
Same issue here, Purpur 1.19.2 no critical damage and all weapons do 1 heart even netherite sword with sharpness 10. Gone back to build 584 and its fixed

**Comment by yeatt** [comment] 2022-08-13 18:36
Hey! Could you also send the build to me as well? The build you're talking about in this post which fixed the combat problem. Message me @ swaghili#0001

**Comment by Pantera07** [comment] 2022-08-14 04:00
I can't reproduce this issue (1.19.2 server)

**Comment by Teslicek** [comment] 2022-08-14 13:37
Same here. Not exactly sure what causes this error, but it also triggered a lot of false-positives in anticheat.

Server (Pufferfish) 1.19, ViaVersion #642, ViaBackwards #284, ProtocolLib #595 (and tons of other plugins).

Havent tried more ProtocolLib versions, but reverting to build #588 fixes the issue.

**Comment by RealTriassic** [comment] 2022-08-15 13:26
Able to reproduce on Purpur git-Purpur-1760.

**Comment by derklaro** [comment] 2022-08-15 13:29
For some information about this see https://github.com/dmulloy2/ProtocolLib/issues/1846#issuecomment-1214962463

**Comment by mfcfbro** [comment] 2022-08-16 05:00
This is definitely an issue on Purpur. It seems that every hit may be calculating as a punch. It takes exactly the amount of swings as each mob has heath to kill them.

**Comment by untuned** [comment] 2022-08-21 02:29
I can confirm this is fixed on the latest development build 598.

**Closed** 2024-06-12 03:02 UTC
