### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by 864063334** [dmulloy2/ProtocolLib#1059] opened 2021-01-08 17:45 UTC
**Describe the bug**
Server thread/ERROR

**To Reproduce**

`[Server` thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:68)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:388)
        at net.minecraft.server.dedicated.DedicatedServer.handler$bbb000$arclight$loadPlugins(DedicatedServerMixin.java:630)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1856)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232)
        at java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:607)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 11 more
  Caused by: java.lang.NullPointerException
        at io.izzel.arclight.common.mod.util.remapper.ArclightInterfaceInvokerGen.shouldGenerate(ArclightInterfaceInvokerGen.java:75)
        at io.izzel.arclight.common.mod.util.remapper.ArclightInterfaceInvokerGen.generate(ArclightInterfaceInvokerGen.java:30)
        at io.izzel.arclight.common.mod.util.remapper.ArclightInterfaceInvokerGen.handleClass(ArclightInterfaceInvokerGen.java:26)
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.remapClassFile(ClassLoaderRemapper.java:282)
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.remapClassFile(ClassLoaderRemapper.java:273)
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.remapClass(ClassLoaderRemapper.java:268)
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.defineClass(ArclightReflectionHandler.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.redirectDefineClassInvoke(ArclightReflectionHandler.java:231)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:603)
        ... 19 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@775ba14[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@273a40e1
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3f8c38e8
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@25e6bfa1
      server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.16.4-1.0.11-SNAPSHOT-feb567a,minecraftVersion=1.16.4}
      file=plugins\ProtocolLib492.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7aa16047
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@b28fd14
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=io.izzel.arclight.common.mod.util.log.ArclightPluginLogger@343ff403
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b492
  Java Version:
    1.8.0_271
  Server:
    arclight-1.16.4-1.0.11-SNAPSHOT-feb567a (MC: 1.16.4)

[01:41:10] [Server thread/INFO] [ProtocolLib/]: Enabling ProtocolLib v4.6.0-SNAPSHOT-b492
[01:41:10] [Server thread/ERROR] [Minecraft/]: ******************************************************
[01:41:10] [Server thread/ERROR] [Minecraft/]: *** ProtocolLib does not support plugin reloaders! ***
[01:41:10] [Server thread/ERROR] [Minecraft/]: *** Please use the built-in reload command!        ***
[01:41:10] [Server thread/ERROR] [Minecraft/]: ******************************************************
[01:41:10] [Server thread/INFO] [ProtocolLib/]: Disabling ProtocolLib v4.6.0-SNAPSHOT-b492`

**Version Info**
ProtocolLib v4.6.0-SNAPSHOT-b492

**Additional context**
[log:]https://pastebin.com/u8Mk1cW3

**Comment by PimvanderLoos** [comment] 2021-01-09 00:34
Duplicate of #1057

**Closed** 2021-06-22 22:30 UTC
