### ISSUE TITLE
Holographic Display Incompatibility

### ISSUE THREAD

**Issue by iShadowboy** [dmulloy2/ProtocolLib#781] opened 2020-02-28 00:55 UTC
Hello to Everybody, I have a bug of compatibility with Holographic, and I'm sure that this is not working for my server, My server is running in 1.8.9 Spigot.

I hope found a Solution, thank you ! ^^

This is the Console Error:

27.02 19:49:29 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
27.02 19:49:29 [Server] INFO java.lang.IllegalStateException: Not implemented
27.02 19:49:29 [Server] INFO at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[HolographicDisplays.jar:?]
27.02 19:49:29 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:183) ~[HolographicDisplays.jar:?]
27.02 19:49:29 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:54) ~[HolographicDisplays.jar:?]
27.02 19:49:29 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:94) ~[HolographicDisplays.jar:?]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.5.0]
27.02 19:49:29 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:29 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:29 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
27.02 19:49:29 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
27.02 19:49:29 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
27.02 19:49:29 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
27.02 19:49:29 [Server] INFO at com.pedrojm96.superlobby.core.CoreReflection.sendPacket(CoreReflection.java:80) [SuperLobby.jar:?]
27.02 19:49:30 [Multicraft] Skipped 30 lines due to rate limit (30/s)
27.02 19:49:30 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
27.02 19:49:30 [Server] INFO java.lang.IllegalStateException: Not implemented
27.02 19:49:30 [Server] INFO at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[HolographicDisplays.jar:?]
27.02 19:49:30 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:183) ~[HolographicDisplays.jar:?]
27.02 19:49:30 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:54) ~[HolographicDisplays.jar:?]
27.02 19:49:30 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:123) ~[HolographicDisplays.jar:?]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.5.0]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:330) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:428) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:112) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:83) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.World.a(World.java:1066) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:970) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.02 19:49:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
27.02 19:49:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]

**Comment by filoghost** [comment] 2020-04-22 18:59
This has been fixed in Holographic Displays, was not caused by ProtocolLib.

**Closed** 2021-06-22 23:27 UTC
