### ISSUE TITLE
NullPointerException in PacketPlayOutNamedSoundEffect in Named_Sound_Effect packet

### ISSUE THREAD

**Issue by NavidK0** [dmulloy2/ProtocolLib#67] opened 2015-03-31 03:03 UTC
[17:48:34 ERROR]: [LibsDisguises] Unhandled exception occured in onPacketSending(PacketEvent) for LibsDisguises
java.lang.NullPointerException
>       at com.comphenix.protocol.reflect.cloning.BukkitCloner.findMatchingClass(BukkitCloner.java:64) ~[ProtocolLib.jar:?]
>       at com.comphenix.protocol.reflect.cloning.BukkitCloner.canClone(BukkitCloner.java:76) ~[ProtocolLib.jar:?]
>       at com.comphenix.protocol.reflect.cloning.AggregateCloner.getFirstCloner(AggregateCloner.java:235) ~[ProtocolLib.jar:?]
>       at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:252) ~[ProtocolLib.jar:?]
>       at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:883) ~[ProtocolLib.jar:?]
>       at me.libraryaddict.disguise.utilities.PacketsManager$2.onPacketSending(PacketsManager.java:538) ~[LibsDisguises.jar:?]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:288) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
>       at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
>       at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:192) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.NetworkManager.handle(NetworkManager.java:141) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.PlayerConnection.sendPacket(PlayerConnection.java:878) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.PlayerList.sendPacketNearby(PlayerList.java:1048) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.PlayerList.sendPacketNearby(PlayerList.java:1029) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.WorldManager.a(WorldManager.java:28) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.World.makeSound(World.java:955) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.playSound(CraftWorld.java:1301) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at com.shampaggon.crackshot.CSDirector$2.run(CSDirector.java:1494) [CrackShot.jar:?]
>       at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-dbe012b-61ef214]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[17:48:34 ERROR]: Parameters:
  net.minecraft.server.v1_8_R2.PacketPlayOutNamedSoundEffect@61a3196[
    a=random.explode
    b=810
    c=816
    d=5452
    e=1.0
    f=126

The issue also occurs whenever I do 
event.setPacket(event.getPacket().deepClone());
 where event is a PacketEvent.

**Comment by dmulloy2** [comment] 2015-03-31 03:19
Duplicate of #66

**Closed by dmulloy2** 2015-03-31 03:19 UTC
