### ISSUE TITLE
Illegal Access Warn

### ISSUE THREAD

**Issue by GeniusH5** [dmulloy2/ProtocolLib#1167] opened 2021-05-21 15:51 UTC
I'm using the latest build for my server version.
I don't know how to check whether it is causing by some other plugin.

The server console Error and the Dump file is in the below pastebin link :
https://paste.gg/p/anonymous/14b6499813d245fa865fea75feb07dce

**Comment by PimvanderLoos** [comment] 2021-05-24 11:14
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by GeniusH5** [comment] 2021-05-24 12:07
> Duplicate of #1162
> 
> This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

What should I do, Sorry I'm new to this Github and all

**Comment by PimvanderLoos** [comment] 2021-05-24 13:42
> > Duplicate of #1162
> > This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
> 
> What should I do, Sorry I'm new to this Github and all

Welcome! :)

Could you try the latest version linked above? 
The WARNING messages you linked should be gone when using that version. If it still happens on the latest version, report back and we can take a closer look at what is happening. 
If the new update does get rid of the WARNING messages you linked, you can close this issue to mark it as resolved.

**Comment by GeniusH5** [comment] 2021-05-25 06:15
Yes, thank you very much. Issue resolved. Mucho Gracias.

**Closed** 2021-05-25 06:15 UTC
