### ISSUE TITLE
INTERNAL ERROR: Cannot compile structure. Disabing compiler.

### ISSUE THREAD

**Issue by SofianeLasri** [dmulloy2/ProtocolLib#1176] opened 2021-05-25 10:25 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'server'
2. Click on 'nothing'
3. Scroll down to 'nothing'
4. See error [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

**Expected behavior**
Protocolib throw an error when players joins the server.

**Version Info**
https://pastebin.com/zV4mnWBk

**Additional context**
I upgraded to Java/OpenJDK 16

**Comment by PimvanderLoos** [comment] 2021-05-25 13:58
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-05-29 17:04 UTC
