### ISSUE TITLE
Help with this exception ClosedChannelException

### ISSUE THREAD

**Issue by DeveloperRic** [dmulloy2/ProtocolLib#259] opened 2016-08-24 09:02 UTC
_Follow this template except for feature requests. Use Pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues

Debug paste link:
http://paste.md-5.net/pubunineyi.avrasm
MainClass:
http://paste.md-5.net/giyesitagi.avrasm
RefreshTimerClass:
http://paste.md-5.net/yuwebabole.avrasm
plugin.yml:
http://paste.md-5.net/yoxasitodo.avrasm
Protocol Dump:
http://paste.md-5.net/yexifabofa.tex

ProtocolLib Version: 4.1.0

Description and relevant errors:
I know this has been fixed, but I find the support for developers using ProtocolLib for the first time, and I understand how packets are supposed to work, but this error baffles me. I know that this error happens then the server sends a Server_Info packet because I cancelled Pong first to test, but the errors were still there, only when I cancelled Server_Info packets did the error stop.

I also know that this is due to sending WrappedServerPings. I am trying to make an animated MOTD plugin, when I send the WrappedServerPing once everything works fine and as expected, but when I send it repeatedly to try to create an animation (after a delay of course), It starts to throw this error.

I am fairly new to the ProtocolLib API and have been googling for over a day trying to find a solution to this. I found out that I need to cancel responses for the ping, but I have no idea how.

Please help.

**Comment by dmulloy2** [comment] 2016-08-24 16:11
Make sure your listener is running async:
````java
manager.registerPacketListener(PacketAdapter.params().optionAsync()...
````

This issue is caused by ProtocolLib holding the packet on the main thread when it is sent from an async thread.

**Comment by DeveloperRic** [comment] 2016-08-24 20:13
I already have the listener set to Async. If you look in the code paste i sent you (http://paste.md-5.net/giyesitagi.avrasm) you will see that in the method 'createProtocolEvent()' I have this piece of code:
new ListenerOptions[] { ListenerOptions.ASYNC }

**Comment by dmulloy2** [comment] 2016-08-25 02:43
Right. There was a similar issue to this in the past.

It's not possible, at least with the method you're using ,to make an animated icon. The channel is closed after the packet is sent, so when you send it again you get a ClosedChannelException. You _might_ be able to dig into some of the Netty code and prevent the channel from closing, but it might be client-side.

**Comment by DeveloperRic** [comment] 2016-08-25 15:34
I'm not trying to make an animated icon in the code I sent you, I was trying to make an animated MOTD, and it would probably not work if I edit the Netty because I plan to release on Spigot and different servers have different configurations.

**Comment by MiniDigger** [comment] 2016-08-26 11:21
Didn't mojang fix the animated logo/motd bug?

**Comment by dmulloy2** [comment] 2016-08-27 00:07
Gotcha. An animated icon would be cool though.

Again, not entirely sure how you would do this. I know there are plugins for Bungee that do it though, might be worth your time to give them a look.

**Comment by Shevchik** [comment] 2016-09-02 07:35
Clients close the connection after receiving server info packet.

**Closed** 2016-09-11 20:53 UTC
Labels: API
