### ISSUE TITLE
Stonecutter dupes items

### ISSUE THREAD

**Issue by ValhallaCraft** [dmulloy2/ProtocolLib#1655] opened 2022-06-15 19:02 UTC
**Describe the bug**
When you put a stack of stone in a stone cutter it does not take the new blocks from the input blocks.

**To Reproduce**
Place Stonecutter
Put stack of stone in Stonecutter
Select the type of stone you want
Unlimited stone cuts

**Expected behavior**
Should take from main stack

**Screenshots**
https://user-images.githubusercontent.com/100648505/173904685-291629c8-fc0a-47b0-8867-447db1f70f1c.mp4

**Version Info**
(https://pastebin.com/6BRWUZci)

**Additional context**

**Comment by Tomhoran628** [comment] 2022-06-15 19:05
I should add that this only happens with essentials installed as well. They said its not them

**Comment by dmulloy2** [comment] 2022-06-16 01:10
Unable to reproduce this with EssentialsX and ProtocolLib. Looking through your protocol dump, the most likely candidate is Shopkeeper's Addon since it modifies window click packets and the like. Closing this as not PL

**Closed as completed by dmulloy2** 2022-06-16 01:10 UTC
