### ISSUE TITLE
ProtocolLib console errors

### ISSUE THREAD

**Issue by chasefailure** [dmulloy2/ProtocolLib#910] opened 2020-07-12 18:23 UTC
ProtocolLib is spamming my console

>.... [04:10:35 ERROR]: java.lang.NullPointerException
>.... [04:10:35 WARN]: java.lang.NullPointerException
>.... [04:10:35 WARN]: at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
>.... [04:10:35 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
>.... [04:10:35 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
>.... [04:10:35 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
>.... [04:10:35 WARN]: at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>.... [04:10:35 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [04:10:35 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
>.... [04:10:35 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:35 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:35 WARN]: at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:35 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:35 WARN]: at su.fogus.engine.nms.packets.PacketManager$1.write(PacketManager.java:107)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
>.... [04:10:35 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
>.... [04:10:35 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
>.... [04:10:35 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
>.... [04:10:35 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
>.... [04:10:35 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>.... [04:10:35 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
>.... [04:10:35 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
>.... [04:10:35 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>.... [04:10:35 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [04:10:35 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [04:10:37 ERROR]: java.lang.NullPointerException
>.... [04:10:37 WARN]: java.lang.NullPointerException
>.... [04:10:37 WARN]: at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
>.... [04:10:37 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
>.... [04:10:37 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
>.... [04:10:37 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
>.... [04:10:37 WARN]: at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>.... [04:10:37 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [04:10:37 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
>.... [04:10:37 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:37 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:37 WARN]: at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:37 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:37 WARN]: at su.fogus.engine.nms.packets.PacketManager$1.write(PacketManager.java:107)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
>.... [04:10:37 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
>.... [04:10:37 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
>.... [04:10:37 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
>.... [04:10:37 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
>.... [04:10:37 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>.... [04:10:37 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
>.... [04:10:37 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
>.... [04:10:37 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>.... [04:10:37 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [04:10:37 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [04:10:39 ERROR]: java.lang.NullPointerException
>.... [04:10:39 WARN]: java.lang.NullPointerException
>.... [04:10:39 WARN]: at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
>.... [04:10:39 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
>.... [04:10:39 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
>.... [04:10:39 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
>.... [04:10:39 WARN]: at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>.... [04:10:39 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [04:10:39 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
>.... [04:10:39 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:39 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:39 WARN]: at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [04:10:39 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [04:10:39 WARN]: at su.fogus.engine.nms.packets.PacketManager$1.write(PacketManager.java:107)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
>.... [04:10:39 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
>.... [04:10:39 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
>.... [04:10:39 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
>.... [04:10:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
>.... [04:10:39 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>.... [04:10:39 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
>.... [04:10:39 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
>.... [04:10:39 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>.... [04:10:39 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [04:10:39 WARN]: at java.lang.Thread.run(Thread.java:748)

I'm running spigot 1.16.1

**Comment by Hysparia** [comment] 2020-07-12 19:36
I'm having the same issue. Can you send me a DM on Discord if you figure out what is causing this issue? MrBerry99#0001

**Comment by DerekWearmouth** [comment] 2020-07-21 03:20
seeing this error as well, any fix found?

**Comment by dmulloy2** [comment] 2020-07-26 04:00
So this is still happening on the latest dev build? Should have been fixed a while ago

**Comment by Stijn-van-Nieulande** [comment] 2020-07-27 19:34
for me this issue is still happening with the latest dev build

**Comment by Stijn-van-Nieulande** [comment] 2020-07-27 19:39
maybe some more details:
```
[19:32:56 WARN]: [ProtocolLib] [Debug] Exception registering converter
java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 0], params=[{Type: class name of net\.minecraft\.(\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*\.)+\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*, Index: null}, {Type: Exact class java.lang.String, Index: 0}, {Type: Exact class java.lang.String, Index: 1}, {Type: Exact class java.lang.String, Index: 4}], paramCount=5}
at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[?:?]
at com.comphenix.protocol.utility.MinecraftReflection.getWorldTypeClass(MinecraftReflection.java:1173) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.addConverter(BukkitConverters.java:1107) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1086) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1127) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:364) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:920) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$200(PacketFilterManager.java:71) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerLogin(PacketFilterManager.java:893) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-89]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-89]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-89]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.PlayerList.attemptLogin(PlayerList.java:663) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.LoginListener.c(LoginListener.java:154) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:369) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-89]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-89]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

```
[19:32:56 ERROR]: java.lang.NullPointerException
[19:32:56 WARN]: java.lang.NullPointerException
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[19:32:56 WARN]: at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[19:32:56 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:32:56 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[19:32:56 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[19:32:56 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[19:32:56 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[19:32:56 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[19:32:56 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[19:32:56 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[19:32:56 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[19:32:56 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:32:56 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:32:56 WARN]: net.minecraft.server.v1_16_R1.SkipEncodeException: java.lang.NullPointerException
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:47)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[19:32:56 WARN]: at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[19:32:56 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:32:56 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[19:32:56 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[19:32:56 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[19:32:56 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[19:32:56 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[19:32:56 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[19:32:56 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[19:32:56 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[19:32:56 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[19:32:56 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[19:32:56 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:32:56 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:32:56 WARN]: Caused by: java.lang.NullPointerException
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[19:32:56 WARN]: at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[19:32:56 WARN]: ... 25 more
```

**Comment by LoneDevilX** [comment] 2020-07-28 16:07
Same here

**Comment by dmulloy2** [comment] 2020-08-04 19:15
Can't reproduce this locally. This issue seems to be chat packets not having their UUID field set, which is fixed in the recent dev builds. Unless there's something else I'm not seeing.

**Comment by vanreek** [comment] 2020-08-05 05:50
This is happening to us and I cannot figure out how to fix it. It happens when switching to a specific server. Only way to join the server is to disconnect to title and rejoin

**Closed** 2020-08-09 14:28 UTC
