### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by DaMadesTx** [dmulloy2/ProtocolLib#1193] opened 2021-06-04 09:05 UTC
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

 java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @725bd9a8
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@72f54ba0[
      targetType=class net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]
      defaultFields={public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname=1, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d=3}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3d4ac1d8[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4ef14e6b
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@47dc2a6c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1f2cd17c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@74838740
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@30c51dad
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@166cce93
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-756,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6f324a13
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1224c40f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@e121590
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@867e3d0[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@3b63ff60=[com.comphenix.protocol.injector.StructureCache$1@3ca13154]}
      listenerLock=java.lang.Object@8118e73
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@16b1b474
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@217fbc11
      reporter=com.comphenix.protocol.ProtocolLib$1@166cce93
      unknownPermGenBean=java.lang.Object@146102fb
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-756 (MC: 1.16.5)

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

Description and relevant errors:

**Comment by PimvanderLoos** [comment] 2021-06-04 09:13
Duplicate of #1162 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-06-04 22:07 UTC
