### ISSUE TITLE
Adding as dependency "disables" my own plugin

### ISSUE THREAD

**Issue by theonlygusti** [dmulloy2/ProtocolLib#461] opened 2018-04-10 13:54 UTC
Debug paste link:

When the server starts up, instead of enabling my custom plugin,

```
[CustomPlugin] Enabling SSM v0.0.1
[CustomPlugin] Enabled!
```

it enables "BukkitExecutors"

```
[BukkitExecutors] Enabling BukkitExecutors v1.0.0
```

And running `/plugins` shows only BukkitExecutors,

```Plugins (1): BukkitExecutors```

My custom plugin is nowhere to be found.

Description and relevant errors:

This happens after I add the ProtocolLib repository and dependency to my CustomPlugin's `pom.xml`:

    <repository>
      <id>dmulloy2-repo</id>
      <url>http://repo.dmulloy2.net/nexus/repository/public/</url>
    </repository>
    
    <dependency>
      <groupId>com.comphenix.protocol</groupId>
      <artifactId>ProtocolLib-API</artifactId>
      <version>4.3.0</version>
    </dependency>

If I just comment out those lines then no issue and my CustomPlugin loads perfectly.

How do I add this as a dependency?

I want to use the LibsDisguises API on my Spigot-1.8.8 server and I need to add this as a dependency first apparently.

I thought copy-pasting the 'Maven repository' lines from the [page over here](https://www.spigotmc.org/resources/protocollib.1997/) would work b/c it says it supports 1.8 all the way up.

**Comment by MiniDigger** [comment] 2018-04-10 15:34
discussion over here, please close this as its not caused by protocollib
https://www.spigotmc.org/threads/using-libsdisguises-in-my-own-plugin-how-to-install-set-up.313656/

**Comment by dmulloy2** [comment] 2018-04-12 16:32
Looks like the thread is doing a fine job of diagnosing this. I don't have any reason to believe this is something to do with ProtocolLib itself.

**Closed by dmulloy2** 2018-04-12 16:32 UTC
