### ISSUE TITLE
1.8.8: PacketType.Play.Server.CHAT not firing for 5.0.0-SNAPSHOT b553

### ISSUE THREAD

**Issue by kangarko** [dmulloy2/ProtocolLib#1588] opened 2022-05-03 12:11 UTC
**Describe the bug**
PacketType.Play.Server.CHAT not firing for 5.0.0-SNAPSHOT b553

**To Reproduce**
Using the code on the image below the latest 5.0.0 snapshots won't fire onPacketSending for any chat message. They still fire the method for commands such as /help. ProtocolLib 4.8.0 works perfectly fine.

![a](https://i.imgur.com/fEHl5xq.png)

https://github.com/kangarko/ChatControl-Red/issues/1870

**Comment by kangarko** [comment] 2022-05-03 12:14
Despite what the image suggests, there should be an additional SENDING PACKET console log after Hey! which there is not, the method is not getting fired at all for chats.

Even if I completely disable chat formatting in ChatControl plugin it still won't get fired.

**Comment by derklaro** [comment] 2022-05-03 12:26
Duplicate of #1576

**Comment by kangarko** [comment] 2022-05-03 12:33
Looks like it, thank you!

**Closed** 2022-05-04 04:21 UTC
