### ISSUE TITLE
SuperVanish bug with Protocollib

### ISSUE THREAD

**Issue by Sansaup** [dmulloy2/ProtocolLib#928] opened 2020-08-05 18:45 UTC
**Describe the bug**
An error in the console, which makes most of the plugin's features (SuperVanish) to not work.

**Expected behavior**
When I do /sv or /v, an actionbar is supposed to appear above my inventory items that says I am in vanish.

**Screenshots**
![bug](https://user-images.githubusercontent.com/69263024/89451001-312dad80-d764-11ea-9422-e4dd0e79d5d7.png)

**Version Info**
https://pastebin.com/2n7BXNs5

**Additional context**
The error is getting spammed, until I go out of vanish.

**Comment by dmulloy2** [comment] 2020-08-05 18:47
Try using the latest dev build and/or updating super vanish.

Also, that version info is just a path, there's no data in it

**Comment by Sansaup** [comment] 2020-08-05 21:06
I don't really understand the meaning of "version". The only thing I know
is that the ProtocolLib is for minecraft version 1.16.1, and the version of
this ProtocolLib is 4.5.1

‫בתאריך יום ד׳, 5 באוג׳ 2020 ב-21:48 מאת ‪Dan Mulloy‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dmulloy2** [comment] 2020-08-06 00:27
You can find the latest development build here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Sansaup** [comment] 2020-08-06 09:54
Thank you very much! It has been fixed.

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-3:28 מאת ‪Dan Mulloy‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Sansaup** [comment] 2020-08-06 09:55
But there is another bug. Now it is spamming in the console "writing UUID
to chat packet"

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-12:54 מאת ‪Lol 12‬‏ <‪
hyperrevolution12@gmail.com‬‏>:‬

**Comment by MiniDigger** [comment] 2020-08-06 10:18
that is most likely caused by a plugin, please run /protocollib dump

**Comment by Sansaup** [comment] 2020-08-06 11:19
The command does not exist neither in the console nor inside the server.

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-13:19 מאת ‪MiniDigger‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Sansaup** [comment] 2020-08-06 11:20
Here is a screenshot of the plugins, maybe one of them is actually the
problem.

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-14:19 מאת ‪Lol 12‬‏ <‪
hyperrevolution12@gmail.com‬‏>:‬

**Comment by Sansaup** [comment] 2020-08-06 11:24
After trying some random commands that I could use with the command
/protocol, I managed to do /protocollib:protocol dump - there is the
pastebin: https://pastebin.com/mBNnuDG9

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-14:20 מאת ‪Lol 12‬‏ <‪
hyperrevolution12@gmail.com‬‏>:‬

**Comment by MiniDigger** [comment] 2020-08-06 13:30
oh sorry, I always mess up the command. its not a plugin causing it, its actually a left over debug message:

@dmulloy2 https://github.com/dmulloy2/ProtocolLib/blob/8c5fbe3298dd41d68b094a54289c002780eb2d4a/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L149

**Comment by Sansaup** [comment] 2020-08-06 14:09
So what am I supposed to do with the script?

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-16:30 מאת ‪MiniDigger‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dmulloy2** [comment] 2020-08-06 17:56
Whoops, should be fixed in the latest build

**Comment by Sansaup** [comment] 2020-08-06 18:52
When is the last build? Will it be uploaded straight away to SpigotMC?

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-20:56 מאת ‪Dan Mulloy‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Sansaup** [comment] 2020-08-06 18:52
When is the latest build? Where will it be uploaded? I am not sure if it
gets uploaded to SpigotMC straight away so...

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-20:56 מאת ‪Dan Mulloy‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dmulloy2** [comment] 2020-08-06 18:58
Build is from the ci.dmulloy2.net link from before. I'm planning on uploading to spigot probably later this week in the absence of any other issues

**Comment by Sansaup** [comment] 2020-08-06 19:03
Alright, thank you very much!

‫בתאריך יום ה׳, 6 באוג׳ 2020 ב-21:58 מאת ‪Dan Mulloy‬‏ <‪
notifications@github.com‬‏>:‬

**Closed** 2021-06-22 22:30 UTC
