### ISSUE TITLE
Unable to download dev version. Link is broken.

### ISSUE THREAD

**Issue by Jonah75** [dmulloy2/ProtocolLib#938] opened 2020-08-16 17:14 UTC
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
"Server Unavailable"

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by daniel11420** [comment] 2020-08-16 20:06
Same here.

**Comment by dmulloy2** [comment] 2020-08-17 14:57
Duplicate of #937

**Closed by dmulloy2** 2020-08-17 14:57 UTC
