### ISSUE TITLE
Disconnecting cause "Error sending packet clientbound/minecraft:update_attributes"

### ISSUE THREAD

**Issue by maskalix** [dmulloy2/ProtocolLib#3065] opened 2024-06-29 21:01 UTC
- [ ] This issue is not solved in a development build

**Describe the bug**
Error sending packet clientbound/minecraft:update_attributes (log below)

**Version Info**
latest ProtocolLib + 1.20.6 (purpur)

**Additional context**
```
[22:32:26] [Netty Epoll Server IO #2/ERROR]: Error sending packet clientbound/minecraft:update_attributes (skippable? false)
--
1340 | io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_attributes'
1341 | at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1342 | at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1343 | at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1344 | at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1345 | at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
1346 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1347 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1348 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1349 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1350 | at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
1351 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1352 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1353 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1354 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1355 | at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
1356 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1357 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1358 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1359 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1360 | at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1361 | at net.minecraft.network.Connection$2.write(Connection.java:759) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1362 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1363 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1364 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1365 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1366 | at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1367 | at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
1368 | at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
1369 | at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
1370 | at net.minecraft.network.Connection.doSendPacket(Connection.java:505) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1371 | at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1372 | at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
1373 | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
1374 | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
1375 | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
1376 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
1377 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
1378 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
1379 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
1380 | Caused by: java.util.ConcurrentModificationException
1381 | at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
1382 | at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
1383 | at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:412) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1384 | at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1385 | at net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:141) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1386 | at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1387 | at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[purpur-1.20.6.jar:1.20.6-2232-f1c87e4]
1388 | ... 39 more
```

**Comment by Ingrim4** [comment] 2024-06-30 12:11
Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

**Comment by maskalix** [comment] 2024-06-30 19:47
`ProtocolLib Dump
Timestamp: 06/30/24 21:46:59

ProtocolLib Version: ProtocolLib v5.3.0-SNAPSHOT-720
Bukkit Version: 1.20.6-R0.1-SNAPSHOT
Server Version: 1.20.6-2232-f1c87e4 (MC: 1.20.6)
Java Version: 21.0.3

ProtocolLib: com.comphenix.protocol.ProtocolLib@3fd82de3[
  statistics=com.comphenix.protocol.metrics.Statistics@e75f841
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@7b38816b
  tickCounter=86757
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@463dbb1c
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@38f4310d
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@196271a2
  commandProtocol=com.comphenix.protocol.CommandProtocol@26ee983c
  commandPacket=com.comphenix.protocol.CommandPacket@da032a6
  commandFilter=com.comphenix.protocol.CommandFilter@14451646
  packetLogging=com.comphenix.protocol.PacketLogging@1ea08a0d
  skipDisable=false
  isEnabled=true
  loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4c5dce9d
  server=CraftServer{serverName=Purpur,serverVersion=1.20.6-2232-f1c87e4,minecraftVersion=1.20.6}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@7c2f29de
  pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7c2f29de
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.3.0-SNAPSHOT-720, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@44ce27c7
  lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2348be8c
  allowsLifecycleRegistration=false
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@26ac12e2[
  plugin=ProtocolLib v5.3.0-SNAPSHOT-720
  server=CraftServer{serverName=Purpur,serverVersion=1.20.6-2232-f1c87e4,minecraftVersion=1.20.6}
  reporter=com.comphenix.protocol.ProtocolLib$1@6983f207
  minecraftVersion=(MC: 1.20.6)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5cc610ef
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3a9c6925
  mainThreadPacketTypes=com.comphenix.protocol.concurrent.PacketTypeListenerSet@7ce15796
  inboundListeners=com.comphenix.protocol.injector.collection.InboundPacketListenerSet@a8481c7
  outboundListeners=com.comphenix.protocol.injector.collection.OutboundPacketListenerSet@6629a910
  registeredListeners=[PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[STEER_VEHICLE[class=ServerboundPlayerInputPacket, id=38]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[USE_ENTITY[class=ServerboundInteractPacket, id=22]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=ServerboundPlayerActionPacket, id=36]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=ServerboundPlayerActionPacket, id=36]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[ADD_RESOURCE_PACK[class=ClientboundResourcePackPushPacket, id=70], ADD_RESOURCE_PACK[class=ClientboundResourcePackPushPacket, id=9]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[DISGUISED_CHAT[class=ClientboundDisguisedChatPacket, id=30]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TR_SEL[class=ServerboundSelectTradePacket, id=45]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[MOUNT[class=ClientboundSetPassengersPacket, id=95]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGH, packets=[OPEN_WINDOW[class=ClientboundOpenScreenPacket, id=51]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=ServerboundSignUpdatePacket, id=53]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[RECIPE_UPDATE[class=ClientboundUpdateRecipesPacket, id=119]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=LOWEST, packets=[RECIPES[class=ClientboundRecipePacket, id=65]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=ClientboundPlaceGhostRecipePacket, id=55]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=ServerboundPlaceRecipePacket, id=34]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[UPDATE_ATTRIBUTES[class=ClientboundUpdateAttributesPacket, id=117]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=ServerboundPlayerInputPacket, id=38]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[OPEN_WINDOW_MERCHANT[class=ClientboundMerchantOffersPacket, id=45]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[RESPAWN[class=ClientboundRespawnPacket, id=71]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@3f2521b1
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@490e9c24
  debug=false
  closed=false
  injected=true
]

Listeners:
ia.m.bn@665295b2[
  lu=ia.m.bl@67aaa67b
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[ASYNC]]
]
ia.m.cj@69d9133b[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[STEER_VEHICLE[class=ServerboundPlayerInputPacket, id=38]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.aH@73306094[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[USE_ENTITY[class=ServerboundInteractPacket, id=22]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.cE@6dcb260e[
  pj=ia.m.cD@31a2bd7a
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=ServerboundPlayerActionPacket, id=36]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.is@6f0a218f[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=ServerboundPlayerActionPacket, id=36]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.lo@13367c11[
  Jv=ia.m.ls@5a262da3
  Jw=ia.m.ln@b8cc93e
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ADD_RESOURCE_PACK[class=ClientboundResourcePackPushPacket, id=70], ADD_RESOURCE_PACK[class=ClientboundResourcePackPushPacket, id=9]], gamephase=PLAYING, options=[]]
]
ia.m.ht@34e1f828[
  AZ=ia.m.hr@6007b7f0
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[DISGUISED_CHAT[class=ClientboundDisguisedChatPacket, id=30]], gamephase=PLAYING, options=[]]
]
ia.m.X@5bf8c912[
  em=ia.m.V@b27d566
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[TR_SEL[class=ServerboundSelectTradePacket, id=45]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.aI@310c3306[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[MOUNT[class=ClientboundSetPassengersPacket, id=95]], gamephase=PLAYING, options=[]]
]
ia.m.hz@4aacb126[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[OPEN_WINDOW[class=ClientboundOpenScreenPacket, id=51]], gamephase=PLAYING, options=[ASYNC]]
]
ia.m.iB@7de93238[
  Dj=ia.m.iA@762e4ef5
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=ServerboundSignUpdatePacket, id=53]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.kx@7e65094[
  Hw=ia.m.kw@2b4bcff7
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[RECIPE_UPDATE[class=ClientboundUpdateRecipesPacket, id=119]], gamephase=PLAYING, options=[]]
]
ia.m.hs@6f7708e5[
  AY=ia.m.hr@6007b7f0
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[]]
]
ia.m.bm@62d67d05[
  lt=ia.m.bl@67aaa67b
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[ASYNC]]
]
ia.m.ky@17951841[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[RECIPES[class=ClientboundRecipePacket, id=65]], gamephase=PLAYING, options=[]]
]
ia.m.kz@db15007[
  Hx=ia.m.kw@2b4bcff7
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=ServerboundPlaceRecipePacket, id=34]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=ClientboundPlaceGhostRecipePacket, id=55]], gamephase=PLAYING, options=[]]
]
ia.m.cF@138a7752[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[UPDATE_ATTRIBUTES[class=ClientboundUpdateAttributesPacket, id=117]], gamephase=PLAYING, options=[]]
]
ia.m.aJ@2510c9e8[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=ServerboundPlayerInputPacket, id=38]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
ia.m.W@31dba8c0[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[OPEN_WINDOW_MERCHANT[class=ClientboundMerchantOffersPacket, id=45]], gamephase=PLAYING, options=[]]
]
ia.m.hu@2cd7072b[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[]]
]
ia.m.aK@376ada97[
  plugin=ItemsAdder v4.0.1-alpha-test-4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[RESPAWN[class=ClientboundRespawnPacket, id=71]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
ItemsAdder by [LoneDev]
`

**Comment by Ingrim4** [comment] 2024-06-30 21:16
This issue is caused by ItemsAdder as stated here: https://github.com/dmulloy2/ProtocolLib/issues/2990#issuecomment-2175649850. So either update ItemsAdder or report this to the authors of ItemsAdder if an update doesn't fix this. (Duplicate of #2990)

**Closed by Ingrim4** 2024-06-30 21:16 UTC
Labels: Waiting
