### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by PhanaticD** [dmulloy2/ProtocolLib#70] opened 2015-04-11 11:29 UTC
using buil 113 : http://pastebin.com/0VE5RFv0

this happens on hunger games servers

**Comment by dmulloy2** [comment] 2015-04-11 20:19
Can you provide a list of plugins using ProtocolLib?

**Comment by PhanaticD** [comment] 2015-04-12 01:24
definitely: AntiAura.jar LibsDisguises.jar  

maybe: LibsHungergames.jar  LibsKitAddOn.jar  LibsMcpvp.jar  NoCheatPlus.jar  TerrainControl.jar

**Comment by PhanaticD** [comment] 2015-04-13 04:39
90% sure its libs disguises had the same issue on a different server without antiaura

**Comment by PhanaticD** [comment] 2015-04-13 04:40
using build 12 from here: http://www.psmc.ca:8080/job/LibsDisguises/

**Comment by dmulloy2** [comment] 2015-04-16 01:38
Does this happen without LibsDisguises installed?

**Comment by PhanaticD** [comment] 2015-04-16 01:42
well its hard to re-produce as it happens randomly on startup, but it has not happened on any of the other servers I have that also have protocollib but not libs disguises

**Comment by dmulloy2** [comment] 2015-04-20 00:24
That tends to be the case with LinkageErrors, they're really difficult to reproduce and fix.  I'd try to update LibsDisguises and ProtocolLib, then try creating a ticket for LibsDisguises.

**Comment by PhanaticD** [comment] 2015-04-28 02:22
yeah still happening :/

**Comment by comniemeer** [comment] 2015-05-03 17:39
We've got the same problem. We have also installed LibsDisguises and a custom plugin we made.

**Comment by dmulloy2** [comment] 2015-05-03 22:02
This is definitely an issue with LibsDisguises. Paging @NavidK0

**Comment by NavidK0** [comment] 2015-05-03 22:21
If this happens when LibsHungergames and LibsDisguises are together, then it's also a possibility that LibsHungergames hasn't been updated. I will look into it.

**Comment by comniemeer** [comment] 2015-05-03 23:32
We haven't installed LibsHungergames. But we use some of the API features in our plugin. Can you tell us what the problem might be and if we have to fix it in our plugin?

**Comment by NavidK0** [comment] 2015-05-03 23:42
Do you have the stacktrace, @comniemeer ? That could help me find it quicker.

**Comment by comniemeer** [comment] 2015-05-04 09:31
Its almost the same as the one posted by @PhanaticD
pastebin.com/B4rxhHRX
Please ignore the lastest part in the error (ReportRTS exception); I think this happens because the player got disconnected unexpectedly.

**Comment by comniemeer** [comment] 2015-05-20 14:11
@NavidK0 Could you please look into it? It also happens with the lastest build (#14) on Spigot 1.8.3.

**Comment by NavidK0** [comment] 2015-07-07 15:20
Just to let you know, I'm fairly certain this has been fixed with the most recent versions of LibsDisguises.

**Closed** 2015-07-07 17:04 UTC
