### ISSUE TITLE
Performance issues with protocollib flushing every packet

### ISSUE THREAD

**Issue by MWHunter** [dmulloy2/ProtocolLib#1415] opened 2021-10-13 20:54 UTC
**Describe the bug**
There are performance issues with protocollib.  It seems to be flushing every packet instead of letting them queue.  This is very inefficient and contributes to it using the most netty resources out of any plugin, even when no plugins are actually using protocollib.

**To Reproduce**
1. Profile a server with spark --thread *, any version from 1.8 to 1.17, and you will see increased netty usage over previous versions.

**Expected behavior**
ProtocolLib should not be using the most netty usage out of any plugin

**Screenshots**
This server has no plugins using ProtocolLib - if you go to the plugins tab, protocollib is taking a large amount of the netty thread despite this.
With protocollib: https://spark.lucko.me/F1VwD1us3W
Without protocollib: https://spark.lucko.me/vLYzWP7PxB

**Version Info**
Version 4.7.0

**Additional context**
This seems to affect all servers using ProtocolLib.

**Comment by WarnDa** [comment] 2022-02-23 20:10
Any news about this ?

**Comment by MWHunter** [comment] 2022-02-23 20:26
This is wrong.  Paper is intelligent about when it flushes entity tracking papers.  While vanilla is inefficient, ProtocolLib undoes Paper optimizations.  Additionally, other plugins are writing without flushing, and forcing the flush will slow the other plugins down.

**Comment by derklaro** [comment] 2022-02-23 20:32
Would love to see the timings report there, I don't see any explicit calls to writeAndFlush or flush anywhere on the first look...

**Comment by WarnDa** [comment] 2022-02-23 20:47
On this flare I got a lot of flushing packets
https://flare.airplane.gg/d05507db

![image](https://user-images.githubusercontent.com/31826333/155405524-9ab76a35-825b-4f62-b4ef-898ae42c6372.png)
![image](https://user-images.githubusercontent.com/31826333/155405615-6b38e22e-c496-4102-9f81-5a725f5cb38c.png)

**Comment by derklaro** [comment] 2022-02-23 21:10
I will take a look in the next day if I can reproduce this, and (if i can reporoduce) dive into it and look for a fix. However on the first look on the screenshots it just looks like a packet write which gets called to *a lot* of handlers in the pipeline... Will see

**Comment by retrooper** [comment] 2022-02-23 21:40
While you are at it, can you also prevent ProtocolLib from immediately calling the vanilla encoder via reflection after they process an outgoing packet? I don't understand why they do it, when it will be done anyway as its passed in the pipeline. Just makes other projects unable to process NMS packets ProtocolLib modified, and it just makes no sense to me. Thanks.

**Comment by retrooper** [comment] 2022-02-23 21:42
Actually already made an issue regarding that https://github.com/dmulloy2/ProtocolLib/issues/1522

**Comment by WarnDa** [comment] 2022-08-17 21:09
So, this is completely fixed ?

**Comment by derklaro** [comment] 2022-08-17 21:13
Should be, didn't notice any reports in a while

**Comment by WarnDa** [comment] 2022-08-18 20:02
Then it's perfect, I'll close it :D

**Comment by MWHunter** [comment] 2022-08-18 21:48
There's still the performance impact of unnecessary sync listeners instead of async, but that's on plugins with 5.0 not ProtocolLib.

**Closed** 2024-06-12 03:02 UTC
