### ISSUE TITLE
encryption error spigot 1.17

### ISSUE THREAD

**Issue by cicatrice74** [dmulloy2/ProtocolLib#1233] opened 2021-06-17 20:37 UTC
Hi, i'm using latest spigot dev 1.17 and latest protocollib dev and latest fastlogin dev and latest authme reloaded dev and i'm getting this error, fastlogin's developer said me it was fixed and it was related to protocollib, but i still have this error.

[19:50:24] [FastLogin Pool Thread #1/ERROR]: [FastLogin] Cannot decrypt received contents
java.lang.RuntimeException: Failed to find NMS class: MinecraftEncryption
	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2003) ~[ProtocolLib.jar:4.7.0-SNAPSHOT-b510]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2003) ~[ProtocolLib.jar:4.7.0-SNAPSHOT-b510]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:217) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:116) [FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:92) [FastLoginBukkit.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[19:50:24] [Server thread/INFO]: /82.56.13.160:49691 lost connection: Disconnected

**Comment by games647** [comment] 2021-06-17 21:25
Duplicate of #1221

**Closed** 2021-06-20 02:23 UTC
