### ISSUE TITLE
ProtocolLib 4.6.0 doesn't work with Holographic Displays 2.4.5

### ISSUE THREAD

**Issue by S4IVin** [dmulloy2/ProtocolLib#1055] opened 2021-01-05 11:43 UTC
**ProtocolLib 4.6.0 doesn't work with Holographic Displays 2.4.5**

**To Reproduce**
**Errror number 1:**
    1. I join the game
    2. HolographicDisplay show this messages: https://pastebin.com/w2yM6uRr
    2. HolographicDisplay spams this message: https://pastebin.com/KJspNcsx (The number 512 increases every time it sends the message
**Error number 2:**
    1. I create a hologram with a {player} or {displayname} line
    2. These two, which on the HolographicDisplay website (https://filoghost.me/docs/holographic-displays/placeholders) say they require ProtocolLib 3.4.6+, do not work

**Expected behavior**
I would expect it to not send all those errors to chat and for {player} and {displayname} to work

**Version Info**
https://pastebin.com/KwGaj3XC

**Additional context**
I thought it might be a ProtocolLib problem because it's still a Snapshot, but if it's a HolographicDisplay problem tell me right away so I'll report the problem to them.
The two plugins are the very latest version and both, if one of the two plugins is removed, they work correctly.

**Comment by x5NaSH** [comment] 2021-01-05 12:38
Same.. But in my case i have libsdisguises and holographic displays and the same error happens.

**Comment by S4IVin** [comment] 2021-01-05 12:45
> Same.. But in my case i have libsdisguises and holographic displays and the same error happens.

It could also be a HolographicDisplay problem, we need to see what they say

**Comment by x5NaSH** [comment] 2021-01-05 13:10
It also happens to me, i have holographic displays and libsdisguises and both have exact error

**Comment by PimvanderLoos** [comment] 2021-01-05 14:04
This is a duplicate of #1053 and has been fixed in filoghost/HolographicDisplays#385

**Comment by strahil211** [comment] 2021-01-05 17:09
Also just got this too https://pastebin.com/vnLuakdQ

**Comment by RavenskyPaul** [comment] 2021-01-05 23:57
> 
> 
> This is a duplicate of #1053
> It has been fixed in [filoghost/HolographicDisplays#385](https://github.com/filoghost/HolographicDisplays/pull/385)

Where we can download the new jar file with the fix?

**Comment by PimvanderLoos** [comment] 2021-01-07 06:48
This issue has been fixed by HolographicDisplays. A download link to their latest dev-build can be found in filoghost/HolographicDisplays#388

**Closed** 2021-01-09 00:04 UTC
