### ISSUE TITLE
I Cant Load ProtocolLib Because My Localhost Server That Include A Folder Name Plugin Remapper On My Plugin Folder

### ISSUE THREAD

**Issue by Sufire367** [dmulloy2/ProtocolLib#3272] opened 2024-10-12 11:25 UTC
[ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[18:17:01 ERROR]: ******************************************************
[18:17:01 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[18:17:01 ERROR]: *** Please use the built-in reload command!        ***
[18:17:01 ERROR]: ******************************************************
[18:17:01 INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679

**Comment by Ingrim4** [comment] 2024-10-21 21:00
Duplicate of #3268

**Closed by Ingrim4** 2024-10-21 21:00 UTC
Labels: duplicate
