### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib

### ISSUE THREAD

**Issue by ErythroCraft** [dmulloy2/ProtocolLib#1363] opened 2021-08-01 15:10 UTC
**Describe the bug**
please read the additional context.

**To Reproduce**
1. start up server

**Expected behavior**
On server start up the console give an ERROR output on latest version of PrtocolLib.

**Screenshots**
no screenshot

**Version Info**
ProtocolLib v3.7.0

**Additional context**
[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
            ===== STACK TRACE =====
  java.lang.RuntimeException: Cannot find class net.minecraft.world.entity.MinecraftServer
        at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1885)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1906)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftServerClass(MinecraftReflection.java:945)
        at com.comphenix.protocol.injector.player.InjectedServerConnection.initialize(InjectedServerConnection.java:134)
        at com.comphenix.protocol.injector.player.InjectedServerConnection.injectList(InjectedServerConnection.java:176)
        at com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler.<init>(ProxyPlayerInjectionHandler.java:148)
        at com.comphenix.protocol.injector.player.PlayerInjectorBuilder.buildHandler(PlayerInjectorBuilder.java:139)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:290)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:202)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.MinecraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1883)
        ... 15 more
            ===== DUMP =====
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLibrary@3049ccaa[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6c58267d
      configExpectedMod=-1
      logger=org.bukkit.plugin.PluginLogger@3b0e05a6
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@44e8b499
      server=CraftServer{serverName=CraftBukkit,serverVersion=3204-Spigot-18c71bf-3ad0fb1,minecraftVersion=1.17.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2d6a0684
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@daaa3ef
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@3b0e05a6
    ]
  Version:
    ProtocolLib v3.7.0
  Server:
    3204-Spigot-18c71bf-3ad0fb1 (MC: 1.17.1)

**Comment by PimvanderLoos** [comment] 2021-08-02 08:48
Duplicate of #1360

**Comment by dmulloy2** [comment] 2021-08-02 16:43
Second time it's happened with 4.7.0 vs 3.7.0 lol

**Closed by dmulloy2** 2021-08-02 16:43 UTC
