### ISSUE TITLE
How fix

### ISSUE THREAD

**Issue by Special-Base** [dmulloy2/ProtocolLib#1185] opened 2021-05-30 06:52 UTC
[14:50:35 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @75967f32
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@151c7f63[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@18871578[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@49b17d3d
        packetListeners=[PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@1e41bdc6, PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@752bba89
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@33a3428
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2336dde2
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@612c042c
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@49fb1572
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-735,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1b32e311
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=5
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@12150a6a
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6bb0f054
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@70bf8d09[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@17ecaa64=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@744e1e30], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@accb66d7=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@4eb20c89]}
      listenerLock=java.lang.Object@226c775b
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@2eb761da
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@2a0c45a2
      reporter=com.comphenix.protocol.ProtocolLib$1@49fb1572
      unknownPermGenBean=java.lang.Object@7484d22e
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-735 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment] 2021-05-31 20:29
Duplicate of #1162

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Closed** 2021-06-04 22:10 UTC
