### ISSUE TITLE
Possible bug with ProtocolLib latest build

### ISSUE THREAD

**Issue by tinyhelus** [dmulloy2/ProtocolLib#3076] opened 2024-07-02 18:36 UTC
- [ ] This issue is not solved in a development build

**Describe the bug**
When i join the server with the latest ProtocolLib (this is why i suspect protocollib to be the issue)
 and for example kill a mob or something or even hold a sword and fly in creative i get kicked from the server.
![image](https://github.com/dmulloy2/ProtocolLib/assets/173596116/c5701887-02d6-4266-af5d-621cd8a53ef4)

**Version Info**
Latest build of ProtocolLib. https://pastebin.com/b2ABmdAz

**Comment by xXkguyXx** [comment] 2024-07-02 18:42
It's probably a plugin on your server (AuraSkills, PlayerAuctions, VoteRewards, WorldGuardExtraFlags, ItemsAdder).  Try without those plugins.

**Comment by tinyhelus** [comment] 2024-07-02 19:48
Nope, doesn't fix the issue sadly.

**Comment by Ingrim4** [comment] 2024-07-02 20:10
Then we can't reproduce the issue because a clean server install with only paper doesn't have the described issue. Please make sure you tested each plugin individually for the error.

**Comment by tinyhelus** [comment] 2024-07-02 21:20
Ok, tomorrow i will try them one by one and see if there is something different.

**Comment by tinyhelus** [comment] 2024-07-03 07:59
Update. The issues was not in any of the plugins above neither ProtocolLib. It was that viaversion plugins had to be updated.

**Comment by Ingrim4** [comment] 2024-07-03 08:50
Ok I assume this issue is resolved than and I will close it.

**Closed by Ingrim4** 2024-07-03 08:50 UTC
