### ISSUE TITLE
Error Message upon going to dev builds

### ISSUE THREAD

**Issue by SulphurSlap** [dmulloy2/ProtocolLib#940] opened 2020-08-16 23:23 UTC
**Describe the bug**
Every time I try to go to https://ci.dmulloy2.net/job/ProtocolLib/, I get this error: https://prnt.sc/u0nl0s
**To Reproduce**
1. Go to 'https://www.spigotmc.org/resources/protocollib.1997/'
2. Click on 'https://prnt.sc/u0nkuf'
3. See error https://prnt.sc/u0nl0s

**Expected behavior**
I expected to go to the dev builds website, but instead I ended up with an error.

**Screenshots**
https://prnt.sc/u0nl0s

**Version Info**
N/A

**Comment by Eutherin** [comment] 2020-08-17 06:11
Same

**Comment by titidelaff** [comment] 2020-08-17 10:23
same

**Comment by Scarlet2031** [comment] 2020-08-17 11:08
true mint

**Comment by dmulloy2** [comment] 2020-08-17 14:56
Duplicate of #937

**Closed by dmulloy2** 2020-08-17 14:56 UTC
